[package]

name = "eulerrust"
version = "0.1.0"
authors = [ "wackywendell@gmail.com" ]

[dependencies]
primes = "^0.2"
rand = "^0.3"
num = "^0.1"

# [dependencies.num]
# git = "https://github.com/rust-lang/num"
